"""
Inference Service - sends prompts to the model and returns responses.
Handles prompt formatting, token counting, and response streaming.
"""

import time
from typing import Generator, Optional

from app.core.config import settings
from app.core.logging_config import get_logger
from app.services.model_manager import ModelManager, ModelStatus

logger = get_logger(__name__)


class InferenceResult:
    """Result from an inference call."""
    
    def __init__(self, text: str, tokens_generated: int, time_seconds: float):
        self.text = text
        self.tokens_generated = tokens_generated
        self.time_seconds = time_seconds
    
    @property
    def tokens_per_second(self) -> float:
        if self.time_seconds > 0:
            return self.tokens_generated / self.time_seconds
        return 0.0
    
    def to_dict(self) -> dict:
        return {
            "text": self.text,
            "tokens_generated": self.tokens_generated,
            "time_seconds": round(self.time_seconds, 2),
            "tokens_per_second": round(self.tokens_per_second, 1),
        }


def _get_manager() -> ModelManager:
    """Get the singleton model manager."""
    return ModelManager()


def _build_chat_prompt(message: str, system_prompt: Optional[str] = None) -> list[dict]:
    """
    Build a chat completion prompt.
    
    Args:
        message: User's message.
        system_prompt: Optional system instruction.
    
    Returns:
        List of message dictionaries for llama.cpp.
    """
    messages = []
    
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    else:
        messages.append({
            "role": "system",
            "content": "You are a helpful AI coding assistant. Provide clear, correct code with explanations."
        })
    
    messages.append({"role": "user", "content": message})
    return messages


def chat(
    message: str,
    max_tokens: Optional[int] = None,
    temperature: Optional[float] = None,
    system_prompt: Optional[str] = None,
) -> InferenceResult:
    """
    Send a chat message to the model and get a response.
    
    Args:
        message: The user's message.
        max_tokens: Maximum tokens to generate (default from settings).
        temperature: Creativity level (0=precise, 1=creative).
        system_prompt: System instruction for the model.
    
    Returns:
        InferenceResult with generated text and stats.
    
    Raises:
        RuntimeError: If no model is loaded.
    """
    manager = _get_manager()
    
    if not manager.is_loaded():
        raise RuntimeError("No model loaded. Load a model first.")
    
    max_tokens = max_tokens or settings.MAX_TOKENS
    temperature = temperature if temperature is not None else settings.TEMPERATURE
    
    prompt = _build_chat_prompt(message, system_prompt)
    
    logger.info(f"Inference: '{message[:50]}...' (max_tokens={max_tokens})")
    start = time.time()
    
    response = manager.current_model.create_chat_completion(
        messages=prompt,
        max_tokens=max_tokens,
        temperature=temperature,
        stop=["<|endoftext|>", "<|im_end|>"],
    )
    
    elapsed = time.time() - start
    text = response["choices"][0]["message"]["content"]
    tokens = response["usage"]["completion_tokens"]
    
    result = InferenceResult(text=text, tokens_generated=tokens, time_seconds=elapsed)
    
    logger.info(
        f"Inference complete: {tokens} tokens in {elapsed:.1f}s "
        f"({result.tokens_per_second:.1f} t/s)"
    )
    
    return result


def chat_stream(
    message: str,
    max_tokens: Optional[int] = None,
    temperature: Optional[float] = None,
) -> Generator[str, None, None]:
    """
    Stream a chat response token by token.
    Yields text chunks as they are generated.
    
    Args:
        message: The user's message.
        max_tokens: Maximum tokens to generate.
        temperature: Creativity level.
    
    Yields:
        Text chunks as they are generated by the model.
    
    Raises:
        RuntimeError: If no model is loaded.
    """
    manager = _get_manager()
    
    if not manager.is_loaded():
        raise RuntimeError("No model loaded. Load a model first.")
    
    max_tokens = max_tokens or settings.MAX_TOKENS
    temperature = temperature if temperature is not None else settings.TEMPERATURE
    
    prompt = _build_chat_prompt(message)
    
    logger.info(f"Streaming: '{message[:50]}...'")
    
    stream = manager.current_model.create_chat_completion(
        messages=prompt,
        max_tokens=max_tokens,
        temperature=temperature,
        stream=True,
    )
    
    for chunk in stream:
        if "choices" in chunk and chunk["choices"]:
            delta = chunk["choices"][0].get("delta", {})
            content = delta.get("content", "")
            if content:
                yield content


def generate_code(
    description: str,
    language: str = "python",
    max_tokens: Optional[int] = None,
) -> InferenceResult:
    """
    Generate code from a description.
    
    Args:
        description: What the code should do.
        language: Programming language.
        max_tokens: Maximum tokens to generate.
    
    Returns:
        InferenceResult with generated code.
    """
    system = (
        f"You are a {language} expert. Write clean, well-documented code. "
        "Return ONLY the code, no explanations unless asked."
    )
    
    return chat(
        message=description,
        system_prompt=system,
        max_tokens=max_tokens,
        temperature=0.2,  # Lower temperature for code generation
    )


def explain_code(code: str, language: str = "python") -> InferenceResult:
    """
    Explain what a piece of code does.
    
    Args:
        code: The code to explain.
        language: Programming language.
    
    Returns:
        InferenceResult with explanation.
    """
    system = "Explain code clearly and simply. Use plain English."
    message = f"Explain this {language} code:\n\n```{language}\n{code}\n```"
    
    return chat(message=message, system_prompt=system, temperature=0.5)